apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: insightface-models
  namespace: insightface
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: insightface-data
  namespace: insightface
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
